### ISSUE TITLE
NameError: name 'avg_reward' is not defined

### ISSUE THREAD

**Issue by chenxi-yang** [SapanaChaudhary/PyTorch-CPO#1]
When running the 
`python algos/main.py --env-name CartPole-v1 --algo-name=CPO --exp-num=1 --exp-name=CPO/CartPole --save-intermediate-model=10 --gpu-index=0 --max-iter=500`, I encountered the following error:

```
Traceback (most recent call last):
  File "algos/main.py", line 229, in <module>
    main_loop()
  File "algos/main.py", line 224, in main_loop
    save_info_obj.dump_lists(avg_reward, num_of_steps, num_of_episodes, total_num_episodes, total_num_steps, rewards_std, env_avg_reward, v_loss_list, p_loss_list, eval_avg_reward, eval_avg_reward_std)
NameError: name 'avg_reward' is not defined
```

**Comment by HasarinduPerera** [comment]
Have you found any resolution yet? @chenxi-yang I am having the same issue.
